#cloud-config
users:
  - name: ${username}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
%{ for key in ssh_keys ~}
      - ${key}
%{ endfor ~}

# Optional: Pakete direkt beim Booten installieren
packages:
  - xe-guest-utilities
  - htop
  - curl

runcmd:
  - [systemctl, enable, --now, xe-guest-utilities]
